### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by elhananby** [gwjensen/SnakeStrikeDocker#1]
Hi Grady, I'm really interested in checking out SnakeStrike, but when trying to build the Docker image according to the instructions I eventually get this error:

> g++ -Wl,-O1 -Wl,--enable-new-dtags -Wl,-z,origin -Wl,-rpath,\$ORIGIN/../lib -o ../../../bin/qdbusxml2cpp .obj/qdbusxml2cpp.o   /tmp/qt-everywhere-src-5.13.0/qtbase/lib/libQt5DBus.so /tmp/qt-everywhere-src-5.13.0/qtbase/lib/libQt5Core.so -lpthread   
make[3]: Leaving directory '/tmp/qt-everywhere-src-5.13.0/qtbase/src/tools/qdbusxml2cpp'
{standard input}: Assembler messages:
{standard input}:9821: Warning: end of file not at end of a line; newline inserted
{standard input}:9822: Error: number of operands mismatch for `movq'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:594: recipe for target '.obj/moc.o' failed
make[3]: *** [.obj/moc.o] Error 4
make[3]: *** Waiting for unfinished jobs....
Makefile:23999: recipe for target '.obj/qinputmethod.o' failed
g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
make[3]: *** [.obj/qinputmethod.o] Error 4
make[3]: *** Waiting for unfinished jobs....
painting/qtriangulatingstroker.cpp: In member function 'void QTriangulatingStroker::arcPoints(float, float, float, float, float, float, QVarLengthArray<float>&)':
painting/qtriangulatingstroker.cpp:454:6: warning: assuming signed overflow does not occur when assuming that (X - c) <= X is always true [-Wstrict-overflow]
 void QTriangulatingStroker::arcPoints(float cx, float cy, float fromX, float fromY, float toX, float toY, QVarLengthArray<float> &points)
      ^
make[3]: Leaving directory '/tmp/qt-everywhere-src-5.13.0/qtbase/src/tools/qdbuscpp2xml'
Makefile:401: recipe for target 'sub-qdbuscpp2xml-make_first' failed
make[2]: *** [sub-qdbuscpp2xml-make_first] Error 2
make[2]: *** Waiting for unfinished jobs....
painting/qpainter.cpp: In static member function 'static bool QPainterPrivate::attachPainterPrivate(QPainter*, QPaintDevice*)':
painting/qpainter.cpp:286:21: warning: 'void QPainter::initFrom(const QPaintDevice*)' is deprecated: Use begin(QPaintDevice*) instead [-Wdeprecated-declarations]
     q->initFrom(pdev);
                     ^
In file included from ../../include/QtGui/qpainter.h:1:0,
                 from kernel/qt_gui_pch.h:59:
../../include/QtGui/../../src/gui/painting/qpainter.h:137:10: note: declared here
     void initFrom(const QPaintDevice *device);
          ^
painting/qpainter.cpp: In member function 'bool QPainter::begin(QPaintDevice*)':
painting/qpainter.cpp:1846:9: warning: 'void QPainter::initFrom(const QPaintDevice*)' is deprecated: Use begin(QPaintDevice*) instead [-Wdeprecated-declarations]
         initFrom(d->original_device);
         ^
painting/qpainter.cpp:1559:6: note: declared here
 void QPainter::initFrom(const QPaintDevice *device)
      ^
painting/qpainter.cpp:1846:36: warning: 'void QPainter::initFrom(const QPaintDevice*)' is deprecated: Use begin(QPaintDevice*) instead [-Wdeprecated-declarations]
         initFrom(d->original_device);
                                    ^
painting/qpainter.cpp:1559:6: note: declared here
 void QPainter::initFrom(const QPaintDevice *device)
      ^
text/qtexthtmlparser.cpp: In function 'void setWidthAttribute(QTextLength*, const QString&)':
text/qtexthtmlparser.cpp:2054:1: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
 }
 ^
text/qtextengine.cpp: In member function 'void QTextEngine::resolveFormats() const':
text/qtextengine.cpp:3472:6: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
 void QTextEngine::resolveFormats() const
      ^
make[3]: Leaving directory '/tmp/qt-everywhere-src-5.13.0/qtbase/src/gui'
Makefile:503: recipe for target 'sub-gui-make_first' failed
make[2]: *** [sub-gui-make_first] Error 2
make[2]: Leaving directory '/tmp/qt-everywhere-src-5.13.0/qtbase/src'
Makefile:50: recipe for target 'sub-src-make_first' failed
make[1]: *** [sub-src-make_first] Error 2
make[1]: Leaving directory '/tmp/qt-everywhere-src-5.13.0/qtbase'
Makefile:53: recipe for target 'module-qtbase-make_first' failed
make: *** [module-qtbase-make_first] Error 2
The command '/bin/sh -c cd "/tmp/qt-everywhere-src-5.13.0" &&     /tmp/qt-everywhere-src-5.13.0/configure -v -platform linux-g++ -prefix /opt/Qt/5.13.0/gcc_64/ -opensource -c++std c++11 -confirm-license -release -nomake tests -nomake examples -skip qtwayland -skip qtlocation -skip qtactiveqt -skip qtandroidextras -skip qtcharts -skip qtdoc -skip qtgamepad -skip qtlocation -skip qtmacextras -skip qtmultimedia -skip qtnetworkauth -skip qtpurchasing -skip qtquickcontrols -skip qtquickcontrols2 -skip qtsensors -skip qtspeech -skip qtsvg -skip qttranslations -skip qtvirtualkeyboard -skip qtwebchannel -skip qtwebengine -skip qtwebglplugin -skip qtwebsockets -skip qtwebview -skip qtwinextras -skip qtimageformats -skip qtgraphicaleffects -skip qtdeclarative  -skip qtremoteobjects -skip qtconnectivity -skip qtxmlpatterns -qt-xcb &&     make -j ${NUM_THREADS_FOR_BUILDS}' returned a non-zero code: 2

Do you have any suggestions?

Best,
Elhanan

P.S.
Oh also, when pulling the pre-built image from DockerHub you have to specify the version (i.e. `docker pull gwjensen/snake_strike:1.0.0)` otherwise it doesn't work

**Comment by gwjensen** [comment]
Hi Elhanan,

What version of g++ are you using? Which OS are you building this on?

**Comment by gwjensen** [comment]
No more info, closing issue.
